### ISSUE TITLE
Discuss UUIDFields

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.8#1]

**Comment by pydanny** [comment]
Ideas to consider
- Suggest it for distributed SQL databases as a primary key. Concern is that more junior coders will use it by default. The problem with UUID PKs is finding sample records is a royal pain in the angular.
- Suggest use of UUID to represent public data in a way that doesn't reflect on the PK structure of the app.

**Comment by imkevinxu** [comment]
I support the ladder. I show the UUID of every object in my API vs ID so it's harder to guess but still keep the ID as PK so it's easy to debug like `Users.object.get(id=1)`

**Comment by michaeljohnbarr** [comment]
Article: [What should I choose for my primary key?](http://databases.aspfaq.com/database/what-should-i-choose-for-my-primary-key.html)

I am curious as to the negatives (outside of the harder to find sample records) this truly is. One thing that I have noticed is that when you use `id = models.UUIDField(default=uuid.uuid4, ...)`, you can no longer check in the model's `save()` method `if self.pk is None`. It always returns a UUID, so an additional query to the database is necessary to determine if the model instance is actually new or not.

**Comment by pydanny** [comment]
From personal experience, unless you are at scale AND really understand SQL/databases outside of an ORM, using UUID as primary key is annoying. My concern for including information about UUID as PK is that simply by listing it, people without those conditions will weigh themselves unnecessarily with it. Therefore, we won't include it in the book.

**Comment by pydanny** [comment]
:ship: specifically obfuscating PKs with UUIDs.
