### ISSUE TITLE
Question: Must model literal strings be unicode?

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.8#10]
Need confirmation, in which case we'll mention it in Chapter 6. Otherwise it is covered in Appendix D.

**Comment by michaeljohnbarr** [comment]
See the [`Django 1.8 Docs on Choosing between __str__() and __unicode__()`](https://docs.djangoproject.com/en/1.8/ref/unicode/#choosing-between-str-and-unicode):

> **If you are on Python 3, you can skip this section because you’ll always create `__str__()` rather than `__unicode__()`.** If you’d like compatibility with Python 2, you can decorate your model class with `python_2_unicode_compatible()`.
> 
> **In particular, rather than giving your model a `__str__()` method, we recommended you implement a `__unicode__()` method.** In the `__unicode__()` method, you can quite safely return the values of all your fields without having to worry about whether they fit into a bytestring or not. (The way Python works, the result of `__str__()` is always a bytestring, even if you accidentally try to return a Unicode object).
> 
> You can still create a `__str__()` method on your models if you want, of course, but you shouldn’t need to do this unless you have a good reason. **Django’s Model base class automatically provides a `__str__()` implementation that calls `__unicode__()` and encodes the result into UTF-8. This means you’ll normally only need to implement a `__unicode__()` method and let Django handle the coercion to a bytestring when required.**

As far as I can tell, the takeaway here is that if you are on Python 2.x, providing a `__unicode__()` method in as unicode would be required. Since the `__str__()` method calls the `__unicode__()` method, all we have to do is this:

# Python 2.x

``` python
from django.db import models

class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)
```

... or this:

``` python
from __future__ import unicode_literals
from django.db import models

class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __unicode__(self):
        return '%s %s' % (self.first_name, self.last_name)
```

# Python 3.x

``` python
from django.db import models

class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)
```

For the sake of thoroughness, here is the `__str__` method found in the class `django.db.models.Model`:

``` python
class Model(six.with_metaclass(ModelBase)):
    ...
    def __str__(self):
        if six.PY2 and hasattr(self, '__unicode__'):
            return force_text(self).encode('utf-8')
        return '%s object' % self.__class__.__name__
```

**Comment by pydanny** [comment]
I think the person who asked this question was not aware of the  `django.utils.encoding.python_2_unicode_compatible` decorator. Since we mention it in numerous places, it is no longer needed.

Makes me wonder why https://docs.djangoproject.com/en/1.8/ref/unicode/#choosing-between-str-and-unicode doesn't list this decorator.
