### ISSUE TITLE
Command Syntax

### ISSUE THREAD

**Issue by bakasaru** [twoscoops/two-scoops-of-django-1.8#106]
Subsection 3.2.2, 2nd paragraph. 

Still learning but my understanding is that without specifying a [destination] the project would be created in the current directory which here conflicts with the hierarchy presented in Example 3.3, since the text indicates 'you would run the command from within the repository root'.

Also, wouldn't the command just be django-admin~~.py~~ startproject, or else preceded by _python_ ?

Great book thus far, enjoying the content!

**Comment by pydanny** [comment]
Yes, if you run `startproject` without specifying a directory, it creates a starter project exactly where you ran it. Furthermore, once you have installed Django, it will allow you to run `django-admin.py startproject` anywhere.
