### ISSUE TITLE
Missing URL at the end of 22.3.6 ("Things That Should Be Tested")

### ISSUE THREAD

**Issue by nickwright80** [twoscoops/two-scoops-of-django-1.8#109]
(If this was deliberate, it's genius…)

In the print edition at 22.3.6 ("Things That Should Be Tested"), the list ends abruptly:

> **Failure**  What happens when any of the above fail? See

… and then nothing :-) I guess you meant to include a URL there? Also, **Failure** should probably have a trailing colon added to match the styling in the rest of the list.

Keep up the good work!

**Comment by pydanny** [comment]
:ship:
