### ISSUE TITLE
Little more explanation is required for Cookiecutter based template

### ISSUE THREAD

**Issue by inoyatov** [twoscoops/two-scoops-of-django-1.8#110]
It is little bit difficult to understand chapter "3.5 Going Beyond startproject". What I am confusing is when I create new application it creates under the repository root folder for cookiecutter based django layout. Should not it be under project root directory? I really stuck in chapter 3.5. :( Can you give some right directions where I should create profiles, ratings and etc. apps? What type of applications should be under repository root and project root? Please help. I cannot wait for next book :(

**Comment by pydanny** [comment]
What is in the book is correct. What is in cookiecutter-django _may_ be correct. What do I mean by that?

See https://github.com/pydanny/cookiecutter-django#for-readers-of-two-scoops-of-django-18

The gist of it is that at times we try new things with cookiecutter-django. We push the limits there so we can determine if practices we are adhering to are correct or not. If we didn't do this, then our practices would become stale and useless. :smile: 

In any case, if you want to use some closer to the book's design, I recommend @imkevinxu's https://github.com/imkevinxu/django-kevin template.

**Comment by inoyatov** [comment]
Thank you for your response. But it is not clear still about "How you are using it?". Where you putting new apps and how you organizing real project. Can you just give real life usage example of it? I will really thankful if you do.
