### ISSUE TITLE
Various typos

### ISSUE THREAD

**Issue by staticshock** [twoscoops/two-scoops-of-django-1.8#115]
Sorry for the limited context, since I don't have the book open anymore, but I jotted these notes down about typos / grammar problems as I was reading Two Scoops of Django 1.8:

| Page number | Text |
| --- | --- |
| 29 | "for an less plain, more customized, real-world Django project template." |
| 93 | "specifically subsection sub-section" |
| 108 | `dict{` |
| 123 | "and their their tests" |
| 232 | "Once a tool of choice is chosen" |
| 256 | "we like to to reorder the steps" |

**Comment by pydanny** [comment]
Fixed p29

**Comment by pydanny** [comment]
> Once a tool of choice is chosen

Ha ha ha. Sob. 

:ship:
