### ISSUE TITLE
Comment in Example 9.6 (Chapter 9 Section 3)

### ISSUE THREAD

**Issue by vabada** [twoscoops/two-scoops-of-django-1.8#116]
In a comment, It refers to the wrong Example (I guess):

```
[...]
from . import utils

# based off the decorator template from Example 8.5
[...]
```

I think it refers to Example 9.5

**Comment by pydanny** [comment]
🚢 :shipit: 

@vabada Do you have a last night so we can provide you full proper accreditation in the 1.11 edition's acknowledgements?
