### ISSUE TITLE
Deprecated Google documentation

### ISSUE THREAD

**Issue by vabada** [twoscoops/two-scoops-of-django-1.8#118]
In Sections 17.3.1 and 17.3.2, a link is provided to https://developers.google.com/webmasters/ajax-crawling
However, "This recommendation is officially deprecated as of October 2015." as it can be seen in the website.
More information: https://googlewebmastercentral.blogspot.com.es/2015/10/deprecating-our-ajax-crawling-scheme.html

**Comment by pydanny** [comment]
:ship:

**Comment by pydanny** [comment]
@vabada Do you want to provide your full name so we can properly credit you in the book?

**Comment by vabada** [comment]
Nah, it's fine. Thanks a lot and keep rocking it! New edition coming soon?

**Comment by pydanny** [comment]
https://github.com/twoscoops/two-scoops-of-django-1.11 

😉
