### ISSUE TITLE
Discuss: 13.3.3 - Example 13.9 page 180 - model or veiw context needed. {% comment %} hidden  {% endcomment %}

### ISSUE THREAD

**Issue by bmsleight** [twoscoops/two-scoops-of-django-1.8#119]
As first read, (and 2nd and 3rd :) )I can not follow the differences between the Bad Example 13.3 and 13.9

IMHO - could do with showing the model or view that does 
User.object.all().select_related("flavours")

Thanks,
Brendan

**Comment by pydanny** [comment]
🚢 :shipit:
