### ISSUE TITLE
select_related() example in Ch. 12.3

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.8#12]
@halfnibble said:

> In 2 Scoops of Django for 1.6, on page 153 (Ch. 12.3.3), you suggest using "select_related()" to minimize hits to the database in template renders. You show the template code, but I'm not sure how I'm supposed to use "selected_related()" in the View. An example View would be GREAT! Thanks.

**Comment by pydanny** [comment]
I believe this is addressed in the image below (note that Templates is now Chapter 13). If this suffices let me know so I can mark this complete.

![screen shot 2015-04-23 at 10 46 04 pm](https://cloud.githubusercontent.com/assets/62857/7313062/9e8bc54e-ea0a-11e4-83fc-4b8885286e86.png)

**Comment by pydanny** [comment]
Is it that we don't describe where to specify `User.object.all().select_related("flavors")` in the view? That would be the `View.get_object(self)` method.

**Comment by halfnibble** [comment]
Yes, I believe I was confused at the time on how to use it in the view.

**Comment by halfnibble** [comment]
Everything is obvious once you know, but can be so confusing beforehand. :)

**Comment by pydanny** [comment]
:ship: Reopen if the current solution isn't good enough.
