### ISSUE TITLE
TimeStampedModel

### ISSUE THREAD

**Issue by maconnell** [twoscoops/two-scoops-of-django-1.8#121]
In 6.1.3 I believe Time**S**tampedModel should be renamed Time**s**tampedModel.

**Comment by pydanny** [comment]
The common convention is `TimeStampedModel`. Any reason why we shouldn't follow it?

**Comment by maconnell** [comment]
I came across this as a beginner with Django, so hadn't seen that there was a Django convention for "TimeStamp" here. Perhaps it is reasonable to keep this convention.

As a Django beginner I was expecting the usual camel case rules to apply - if I make something from a timestamp, and a model, I get a TimestampModel. But looking at TimeStampedModel it can give the feeling that it's made from a Time and a Stamp, not a timestamp. So, although in this case it was obvious to me that it was a "timestamped model", it wasn't obvious why it wasn't called that. But now I know ;-)

**Comment by pydanny** [comment]
:smile:
