### ISSUE TITLE
5.5.2 Using Multiple Requirements Files With Platforms as a Service (PaaS) is Missing

### ISSUE THREAD

**Issue by edwardotis** [twoscoops/two-scoops-of-django-1.8#122]
There is no information in 5.5.2 or Chapter 30 about "Multiple Requirements Files With Platforms as a Service (PaaS)". It's like a placeholder with a pointer to Chapter 30, and neither has any information on this topic.

Here's the  February 2016 response on the topic with my paas, Heroku.

"There is no way to currently do this on Heroku from the same codebase, without hacking a bin/pre_compile script to move things around before $ pip install occurs." - Heroku Support Staff

More discussions from years ago where Heroku declined to support multiple requirements files:
https://discussion.heroku.com/t/how-to-handle-requirements-txt-for-a-staging-and-production-environment-on-heroku/295/7
https://github.com/heroku/heroku-buildpack-python/issues/80

It would be great if 2 Scoops could provide the missing bin/pre_compile script necessary to use multiple requirements files on Heroku. And at a minimum, don't leave in the empty chapter that has no solution to this problem.

Thanks,

Ed

**Comment by pydanny** [comment]
While I understand your problem, we're not going to fill in missing components of Heroku's platform. Here's why:

* Heroku's API changes. If we document how to hack their system, that makes the book dated as soon as they change their API
* Heroku seems to think that single requirement files are the way to go. They prefer a smaller app design than how most of us build Django apps. That makes sense - they bill by the dyno. Nothing wrong with that, their billing system allows them to fund a popular PAAS.
* It's pretty easy to write a script that combines your requirements into one file. We do that for Cookiecutter Django. Why not use that method?
