### ISSUE TITLE
Fix index overlap

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.8#14]
![screen shot 2015-04-11 at 9 03 40 pm](https://cloud.githubusercontent.com/assets/62857/7104345/49d45406-e08e-11e4-83be-6646c90407c4.png)

**Comment by audreyfeldroy** [comment]
I've isolated it to the Security chapter. Looks like a bounding box issue.

**Comment by audreyfeldroy** [comment]
Fixed!

**Comment by pydanny** [comment]
:heart:
