### ISSUE TITLE
13.7.2 - Common conventions - endblock convention

### ISSUE THREAD

**Issue by spedy** [twoscoops/two-scoops-of-django-1.8#141]
In the section 13.7.2 you recommend to end all blocks with block names eg. `{% endblock javascript %}`, yet in your [code](https://github.com/twoscoops/two-scoops-of-django-1.8/blob/master/code/chapter_13_example_15.html#L39) you don't apply the principle for some reason.

**Comment by pydanny** [comment]
"some reason"

The reason is an oversight on our part. 😝

**Comment by pydanny** [comment]
🚢 :shipit:
