### ISSUE TITLE
[Chapter 2.3] Little mistake with description of requirements file

### ISSUE THREAD

**Issue by pszpetkowski** [twoscoops/two-scoops-of-django-1.8#147]
There is a little inaccuracy about the pip requirements file in following part of the chapter:

> It contains the name and desired version of each package.

Providing package version is completely optional and calling it _desired version_ is rather oversimplification as well. If I had to somehow classify it I'd rather call it a version range or version conditionals, so if I had to I'd rename this sentence into something like that:

> It contains the name and optionally suitable version range of each package.

**Comment by pydanny** [comment]
:ship:
