### ISSUE TITLE
[Chapter 2.4] Recommend GitLab as a code hosting service

### ISSUE THREAD

**Issue by pszpetkowski** [twoscoops/two-scoops-of-django-1.8#148]
In past few years GitLab has became awesome development environment with git hosting and lots of other useful features like code review, on-site CI and deployment to production. Not to mention that it's [open source project](https://gitlab.com/gitlab-org/gitlab-ce). Therefore I find it extremely convenient for open source development and I think that pointing it out in the book as the third code hosting service would give people more choice.

**Comment by pydanny** [comment]
Where's the +100 on this thing?

😺

**Comment by pydanny** [comment]
Boom! Done! Yeah! You definitely get a credit for suggesting it. 😄 

:ship:
