### ISSUE TITLE
example 28.3

### ISSUE THREAD

**Issue by bernatbonet** [twoscoops/two-scoops-of-django-1.8#152]
When we execute this part of code

`>>> user = get_user_model().get(username="audreyr")
`

![image](https://cloud.githubusercontent.com/assets/440395/19600400/287495a8-97a5-11e6-87e1-f522ffa57176.png)

We must change to:

`>>> user = get_user_model().object.get(username="audreyr")

![image](https://cloud.githubusercontent.com/assets/440395/19600484/85279f0c-97a5-11e6-94ef-a2b8313f00a7.png)

`

**Comment by pydanny** [comment]
:ship: :shipit:
