### ISSUE TITLE
22.4 Integration tests

### ISSUE THREAD

**Issue by michael-sanders** [twoscoops/two-scoops-of-django-1.8#155]
In section 22.4 where you talk about the downsides of integration tests, the following sentence does not make sense (in the context):

> We've yet to work on a significant project where at least one person seemed forever blocked from running them successfully.

This would make more sense if it read:

> We've yet to work on a significant project where at least one person wasn't seemingly forever blocked from running them successfully.

**Comment by pydanny** [comment]
:ship:
