### ISSUE TITLE
2scoops.co Site Down

### ISSUE THREAD

**Issue by mattayes** [twoscoops/two-scoops-of-django-1.8#157]
Hi folks:

The whole [2scoops.co](http://www.2scoops.co/) site is down. Here's the error message I'm currently getting for a given page:

![ch0_provide_the_best_material_change_list_error](https://cloud.githubusercontent.com/assets/8622473/22615323/649b3cae-ea47-11e6-940b-a9f2b04f2ab7.PNG)

I think the issue may be related to this: http://stackoverflow.com/questions/31902776/mysterious-cloudfront-bad-request.

**Comment by pydanny** [comment]
Looking into it.

In the meantime, you can access those links by getting rid of the 'www'
prefix.

**Comment by mattayes** [comment]
@pydanny Alright, so this is almost definitely something DNS-related. For most requests, going to [http://2scoops.co](http://2scoops.co) simply redirected me to http://www.2scoops.co, which showed the same error as above (except for the `Request ID`). However, on one attempt a request went through and redirected to https://www.twoscoopspress.com/.

**Comment by pydanny** [comment]
Okay, should be resolved. Please try again.

**Comment by mattayes** [comment]
Works like a charm. Thanks, @pydanny!
