### ISSUE TITLE
21.10.10: Dead link

### ISSUE THREAD

**Issue by mattayes** [twoscoops/two-scoops-of-django-1.8#160]
Hi folks:

I believe I found a dead link:

* Chapter 21 (Django's Secret Sauce: Third-Party Packages)
* Section: 10: (What Makes a Good Django Package?)
* Subsection: 10 (Uses the Broadest Requirements Specifiers Possible)
* Link: http://www.pip-installer.org/en/latest/logic.html#requirement-specifiers
* Error Page (on redirected URL https://en/latest/logic/#requirement-specifiers):
![21_10_10_bad_link](https://cloud.githubusercontent.com/assets/8622473/22630617/69a02a0e-ebb2-11e6-9a96-be7a58f99ae9.PNG)

http://www.pip-installer.org redirects to their new website, https://pip.pypa.io/en/stable/. Going to https://pip.pypa.io/en/stable/logic.html redirects to https://pip.pypa.io/en/stable/logic/:
![21_10_10_logic_screen](https://cloud.githubusercontent.com/assets/8622473/22630656/0790f9dc-ebb3-11e6-8c28-3a20f4a3cb81.PNG)

Let me know if this needs any more clarification!

**Comment by pydanny** [comment]
:ship:
