### ISSUE TITLE
24.2.2: Bad Link

### ISSUE THREAD

**Issue by mattayes** [twoscoops/two-scoops-of-django-1.8#164]
Hi folks, I think I found a bad link:

Chapter: 24 (Finding and Reducing Bottlenecks)
Section: 2 (Speed Up Query-Heavy Pages)
Subsection 2: Reduce the Number of Queries
* Link: http://2scoops.co/1.8-test-num-queries
* Issue: Redirects to https://docs.djangoproject.com/en/1.8/topics/testing/overview/#django.test.TestCase.assertNumQueries, however there is no anchor for `django.test.TestCase.assertNumQueries`, so we start at the top of the page.
* Recommended redirect: https://docs.djangoproject.com/en/1.10/topics/testing/tools/#django.test.TransactionTestCase.assertNumQueries

Let me know if this needs more clarification!

**Comment by pydanny** [comment]
Thanks for identifying the problem! I've changed the direction of the 1.8 link so it goes to https://docs.djangoproject.com/en/1.8/topics/testing/tools/#django.test.TransactionTestCase.assertNumQueries.
