### ISSUE TITLE
2.3 - broken link

### ISSUE THREAD

**Issue by alenajk** [twoscoops/two-scoops-of-django-1.8#165]
In section 2.3, the Simon's Rock PYTHONPATH link appears to be broken

Link: http://cs.simons-rock.edu/python/pythonpath.html

Looks like that content has been moved to the following location:
http://hope.simons-rock.edu/~pshields/cs/python/pythonpath.html

**Comment by pydanny** [comment]
:ship: in 1.11 with credit shared. @alenajk, if you want your real name in the book, please let me know what it is.

**Comment by alenajk** [comment]
Github handle is fine - thanks!
