### ISSUE TITLE
32: Grammatical Error

### ISSUE THREAD

**Issue by mattayes** [twoscoops/two-scoops-of-django-1.8#167]
Hi folks, I believe I found a grammatical error:

* Chapter: 32 (Continuous Integration)
* Paragraph, with error bolded:
> *Automation integrates the code into the project, building out the project. Any failures during the build process and **the commit*** **are** ***rejected**.*
* Paragraph, with error replaced:
> *Automation integrates the code into the project, building out the project. Any failures during the build process and **the commit*** **is** ***rejected**.*

Let me know if this needs any clarification!

**Comment by pydanny** [comment]
Thanks @mattayes, but this has already been addressed in the forthcoming 1.11 release of the book. 😉

**Comment by mattayes** [comment]
Good to hear! Looking forward to the release!
