### ISSUE TITLE
Inline formsets - Multiple forms for one view. Ch 9, 10, or 11.

### ISSUE THREAD

**Issue by halfnibble** [twoscoops/two-scoops-of-django-1.8#18]
I am desperately requesting some guidance be added on the use of inline formsets. I envision this would fit into either chapters 9, 10, or 11.

There is a lot of documentation on what inline formsets are, but I can't find any clear guidance on how to implement them, or what the best practices are. 
https://docs.djangoproject.com/en/1.8/topics/forms/modelforms/#inline-formsets
# The main issues being:
1. Where is the best place to validate the inline formsets?
2. How and when do you save the inline formsets?
3. What is the best way to handle displaying errors for the inline formsets?
# Use case:

I have an ice cream store with a model for Order's, and another model for IceCreamRecipe's. Since customers are free to create multiple, custom concoctions in their Order, I want a single view that processes the Order form, and allows for one or more IceCreamRecipe form instances to be added to it.

These IceCreamRecipe's are linked to the Order by a ForeignKey. We will use Django's inlineformset_factory to create multiple IceCreamRecipe forms. Then verify we can make the IceCreamRecipe's and save them with the Order.
# Some research I've done:
1. Django Oscar's use of handling multiple formsets. They override form_valid() and form_invalid() to point to their custom form processing method. It works, but seems unconventional. 
   https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/dashboard/catalogue/views.py
2. Here is a gist, which I've used to get formset errors to display, but it seems off too:
   https://gist.github.com/neara/6209563
3. This person is overriding get() and post() methods from a CreateView. Again, it seems odd:
   http://kevindias.com/writing/django-class-based-views-multiple-inline-formsets/

Please help clarify some best practices on inline formsets. Thank you.

**Comment by halfnibble** [comment]
In case anyone is curious, I ended up modifying a CreateView's post() method to run a call to formset.is_valid() right after running form.is_valid(). Then, I redirect to a custom form_valid() or form_invalid() method. This still seems "wrong."

**Comment by tthayer** [comment]
@halfnibble Yes, it is a huge pain, especially once you start trying to implement dynamic elements. I went through Two Scoops 1.6 several times, desperately hoping to see something in there regarding properly implementing inline formsets. I've ended-up using a solution like yours (from the sound of it) and it is super janky and totally not DRY to be hacking up a GCBV like that for each view you want to implement a formset in.

**Comment by pydanny** [comment]
Here is the problem with us adding information on formsets:
1. I use them rarely, Audrey less so. This puts us in the uncomfortable position about writing what we don't know that well.
2. When face with multiple forms on a single views, I either try and split the view into several views, or try to determine where I went wrong with the user interface/design.
3. I personally believe that they are difficult to get completely right, have edge cases that can be hard to manage, and create quite complicated user interfaces.
4. There is almost no thought consensus on their use. Who do we consult for expertise? The one person I know who has delved extensively into them in their writings, Nathan Yergler, has similar concerns about using them.

Should we warn against their use? I don't know. Should we write about them? I'm not sure. If we were going to write something today it might not make you happy. The total gist of what we would say is:
1. Formsets are tricky and hard to get right. Keep them simple and write tests!
2. If you are using formsets, maybe you have a UX or design issue. Step back and determine if you really need them.
3. Here are a few links to resources that date back X years.

We're not sure what to do. We don't want to disappoint, but in this case we're in a weird position.

**Comment by tthayer** [comment]
If this is the wrong place to ask, let me know.

How do you recommend dealing with dependent models in the same form? I have some child models that need to be unique to their parent and need to be added at the same time the parent is and there needs to be the ability to add multiple children at the time of creation, similar to how the admin site works. Right now I have a spidery inlineformset_factory kludge to make this work. It would be awesome if there was a simpler way to deal with this.

**Comment by pydanny** [comment]
I have a crazy idea. What if I wrote a book that focused on Django forms, with a tentative title of '_Hacking Django Forms to Pieces_'? That way I would have the space and forum to provide answers to the questions in this thread and more. I could use that to justify working with inline formsets.

I talked to Audrey about this idea. This would just be me. Audrey would support it as illustrator, proof-reader, and sanity-checker. What that means is the writing voice would be different (the Two Scoops of Django voice is an combination of the two of us). 

Is that something people would consider purchasing?

**Comment by halfnibble** [comment]
Absolutely.

Excellent idea. I was just thinking, I don't think you should warn people
_not_ to use formsets--they definitively have good use cases. However, you
may warn that documentation on implementation is scarce, and that best
practices have yet to develop a consensus.

Maybe we could get the authors of formsets, inline formsets, model
formsets, etc. together to hash out their visions for the implementation.
Also, we might be able to get guys like the Django Oscar team to chime in
on how they used inline formsets in their ecommerce products.

On Wed, Apr 22, 2015 at 12:50 PM, Daniel Greenfeld <notifications@github.com

**Comment by stepmr** [comment]
I would definitely purchase this too :+1:

**Comment by tthayer** [comment]
I would definitely buy that book!

**Comment by yakky** [comment]
Just count one more book sold in advance
