### ISSUE TITLE
Information about testing external APIs

### ISSUE THREAD

**Issue by iyn** [twoscoops/two-scoops-of-django-1.8#19]
What about some info about testing external services/APIs? Most of the services have caps on the number of requests, testing takes more time if we need to hit the web etc. You can check out these cool packages:
https://github.com/gabrielfalcao/HTTPretty
https://github.com/kevin1024/vcrpy (this one is really great)

Let me know if I should stop posting new issues ;)

**Comment by rnevius** [comment]
This doesn't really have anything to do with Django.

**Comment by phalt** [comment]
This is out of the scope for two scoops (see what I did there?), it'd be more suited for a book on testing.

**Comment by iyn** [comment]
Well, I thought that since Django lets you build complex webapps, and more often than not you'll use external APIs, it could be good to mention best practice for testing external services. Anyway, just a thought.

**Comment by pydanny** [comment]
@iyn By all means, keep up with the suggestions. Please keep in mind we can't make any promises about included content.

As for this issue of testing against APIs, we were debating explaining a bit about integration tests and tools like runscope, requestb.in, and others in our testing chapter. I wonder if @hjwp would be willing to weight in.

**Comment by pydanny** [comment]
We cover this in a mix of using Mocks and integration tests. @phalt (A TSD1.8 reviewer), is it covered in depth enough for me to close this issue?

**Comment by phalt** [comment]
@pydanny The stuff is the most recent review copy is great.

**Comment by hjwp** [comment]
Here's a relevant talk from Pycon: http://pyvideo.org/video/3462/cutting-off-the-internet-testing-applications-th

What I tend to do is try and build a functional test that exercises the real service (albeit perhaps in a sandbox (thinking stripe/paypal here) (although paypal's sandbox is the worst thing ever)), and then have that run in CI once or twice a day, or whenever the feature is being actively worked on, which keeps us fairly safely inside any api limits.  unit tests can then use mock.    i haven't played with any of the funky vcr/httpretty libraries tho, so definitely check out Ian's talk...

**Comment by phalt** [comment]
@hjwp There is mention of integration testing that should be ran every so often. It's a great practice (and helps quell paranoia about if it does actually work when all your other tests are mocked).

**Comment by pydanny** [comment]
@hjwp, @phalt For our testing chapter, we tried to channel you into the pages. And of course we pointed at your excellent book. :smile:
