### ISSUE TITLE
Suggestion: Testing standalone Django apps

### ISSUE THREAD

**Issue by uranusjr** [twoscoops/two-scoops-of-django-1.8#20]
I recently started a new Django package project, and find myself struggling (again) to setup a good testing environment. The official documentation is nice, but I’d really wish there’s a more complete writeup on what I should do to set things up. When do I call `django.setup()`? `settings.configure()`? When do I use `override_settings`, and when should I not? And how do I use it, anyway?

2SoD already mentioned how to test a Django project (website), but not how to test one standalone Django app. This might be a nice addition to the third-party packages chapter, IMHO.

**Comment by phalt** [comment]
:+1: I often have to build some hacky test suite to test my django apps in a django project. If there was a best practice suggested by Two Scoops I'd be super happy :D

**Comment by pydanny** [comment]
This is :boat:, not a :ship:. That's because we have it marked internally as something coming after the initial release of the book. It will be Section 10 of the Testing Chapter.
