### ISSUE TITLE
Suggestion: Cover readability of querying

### ISSUE THREAD

**Issue by kracekumar** [twoscoops/two-scoops-of-django-1.8#21]
Django supports different way to query using ORM like `User.objects.filter(email__ne='johndoe@example.com), User.objects.exclude(email='johndoe@example.com) and using Q object.` Sometimes these become super confusing when mixed together. Advise pros and cons of each one and when to/not use.

**Comment by pydanny** [comment]
Love the readability suggestion! :heart:

**Comment by pydanny** [comment]
d'oh. I implemented this as taking advantage of lazy evaluation, not choosing which way to get a result. Oh well, I'll see about adding in more content.

**Comment by alasdairnicol** [comment]
Django doesn't have a `__ne` operator (although it can be implemented as a [custom lookup](https://docs.djangoproject.com/en/1.8/howto/custom-lookups/#a-simple-lookup-example) in Django 1.7+)

There's some discussion on [Django ticket 5763]

**Comment by pydanny** [comment]
:ship:
