### ISSUE TITLE
Suggestion: SaaS Primer

### ISSUE THREAD

**Issue by stepmr** [twoscoops/two-scoops-of-django-1.8#23]
From what I remember there is actually not a lot of resources for beginners building boilerplate for SaaS projects with Django.  This is probably beyond the scope of the book, but could be super helpful...

Could cover stripe integration, plans and billing, subdomain/cname anchoring etc

**Comment by pydanny** [comment]
Yes, a general SaaS primer is out of scope. I think what might work better is a separate book on the subject. It's not a topic we want to cover, but perhaps someone else should? ;)

Also, for stripe integration, what about my own dj-stripe? https://github.com/pydanny/dj-stripe :moneybag:
