### ISSUE TITLE
Additions to 1.8 Edition

### ISSUE THREAD

**Issue by 0x0c72** [twoscoops/two-scoops-of-django-1.8#26]
Repositing in separate issue for organization and clarity.

I’m not sure I made this specific suggestion.  I do have a question though, something I would like to see in the next book.  More in depth into creating/consuming REST API’s.  Creating/consuming SOAP transactions.  And a chapter or two on using Django with js frameworks like bootstrap and angular.  And about a chapter on tools, I know you have one, but some more in depth on usage, tools like bower, gulp, grunt, and CSS preprocessors like SCSS.  A chapter on web servers would help a lot too.  Such as gunicorn with nginx reverse proxy, apache with mod_wsgi, and others.  They are mentioned but just a bit more in depth with examples and some gotchas and such.  If you could include the best practices for all of these with examples. Gotchas, and informations then this would be the best programming book ever.  Although it already sort of is ☺ More suggesitons are diving into  changes from 1.6. Such as urlpatterns = [] vs urlpatterns = patterns("". etc) not sure if that's a 1.8 thing though but many people don't understand the differenence.  A chapter on debugging certain issues would help, e.g. 500 errors.  Maybe mention why admindocs often breaks sites at times or why it could.  Explain admin.autodiscover().  You guys do a great job offering file paths for settings.py, but don't explain how they work exactly.  A quick overview and reference as to what the  settings do (TEMPLATE_URL, TEMPLATE_DIRS, STATIC_URL, etc.).  Also the splitting files for settings.py is great.  Although I always have trouble with it unless I specify settings. But you don't really cover what exactly needs to be added to DJANGO_MODULE_PATH and PYTHONPATH and where to set them.  

On a  side now I often have confusion as to which  part of the project to put my templates dir, static dir, etc. in.   I usually do the project root, but when there are multiple apps, I'm not sure how to make it work.  Assuming more than  one app has templates and static date.  Touching on that would be nice.  

Take Care, can’t wait for 1.8 book, love the books.

P.S. the 1.8 book comes out in april?  April is almost over.  I just bought the 1.6 book and found out that 1.8 comes out this month ;( I’ll still buy it though.  When will it actually be available on amazon or wherever?

**Comment by pydanny** [comment]
Thanks for the suggestions and feedback! I'm closing this as this is actually many issues rather than just one. However, you've given us a lot to think about. :smile:
