### ISSUE TITLE
Question: Lists of figures and tables, keep in front or move to back?

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.8#27]
One of our tech reviewers suggested we move the List of Tables and List of Figures to the back, right before the index. What would you prefer, front or back?

**Comment by brouberol** [comment]
I'd say back too. I feel it's more engaging to dive into the content right away, than having to go through several index pages. 

Keep up the great work :+1:

**Comment by phalt** [comment]
I'm inclined to suggest the back, it's where I'd look for the index, so keeping all the "lookup" things in one place is a good idea.

**Comment by grantmcconnaughey** [comment]
I vote for back. Get us to the content right away.

**Comment by initialkommit** [comment]
I think that it's better to move them to the back of the book. um.. I feel more comfortable to look them up on the back. and I'm also familiar to

**Comment by pydanny** [comment]
:ship:
