### ISSUE TITLE
Refactor the `Consuming REST APIs in Templates` chapter 

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.8#3]
Django moves a snails pace compared to how REST is consumed in templates. Simply put, the JavaScript framework world moves very fast. What is a good idea now, won't be the right way to do things within a matter of months, possibly weeks.

Considerations:
- Determine the best place to provide JavaScript front-end information and list it.
- Link to google's formal documentation on creating sitemaps.
- Link to google documentation on indexing JavaScript: https://www.google.com/webmasters
- Remove the `AJAX and the CSRF Token` code sample and link to the relevant Django documentation.

**Comment by pydanny** [comment]
:ship:

**Comment by fynali** [comment]
@pydanny, thank you for all your and @audreyr's efforts in the Two Scoops django book; we are ever so grateful!

Keep up the great work!
