### ISSUE TITLE
Add silk

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.8#32]
@mtford90's awesome project needs to go into the bottlenecks section.

https://github.com/mtford90/silk/tree/master/silk

**Comment by mtford90** [comment]
;) honoured!

**Comment by pydanny** [comment]
:ship: Love your project @mtford90 :)

**Comment by mtford90** [comment]
Cheers @pydanny, always happy to hear people are finding it useful :D
