### ISSUE TITLE
Putting a django site offline

### ISSUE THREAD

**Issue by abhaga** [twoscoops/two-scoops-of-django-1.8#37]
Chapters 27 & 28 that discuss deployment do not touch upon the mechanisms for putting a site offline. While this can be done at web server level but more often then not, the requirement is to let admin and staff login while putting it offline for others which requires a solution within Django.

I feel it is a good practice to have this sorted out since the beginning.

**Comment by pydanny** [comment]
Got any suggested packages to aid in this?

We've used a fork of @craigkersteins' https://github.com/craigkerstiens/django-db-tools, but that's getting quite old. Doesn't use Django's new middleware.

**Comment by abhaga** [comment]
We have been using https://github.com/shanx/django-maintenancemode on couple of our projects. There is https://github.com/alsoicode/django-maintenancemode-2 which seems more up to date but I haven't used it.

**Comment by pydanny** [comment]
Once again, thank  you @abhaga for the contribution! 

🚢
