### ISSUE TITLE
More django.db.migrations content

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.8#38]
From Markus Holterman:
- Django might create multiple initial migrations if i.e. there are Circular references between models.
- cover "unmanaged models" (Model._meta.managed = False): People find it quite irritating that migrations are still created for unmanaged models. When applying the migrations however, they don't produce any SQL code.

**Comment by pydanny** [comment]
Reversible migration.RunPython() calls:

``` python
migrations.RunPython(my_special_function, lambda x, y: x)
```

**Comment by fodra** [comment]
Totally agree with this one. Topic on refactoring monolithic models.py and breaking it up into multiple apps. Tough one.

**Comment by pydanny** [comment]
🚢
