### ISSUE TITLE
Bookmarks in early release PDF

### ISSUE THREAD

**Issue by gkeller2** [twoscoops/two-scoops-of-django-1.8#41]
The chapters in the PDF bookmarks (or table of contents) are only identified by title instead of chapter number and title. It'd be great if the chapter number could be included, given that it increases its usefulness.

**Comment by pydanny** [comment]
:+1: I could use this too. Why the heck haven't we done this yet already?

**Comment by xblitz** [comment]
also when I import the PDF to my Google Books library it doesn't seems to recognize the chapters. maybe it's related

**Comment by pydanny** [comment]
:ship: YEAH!

![screen shot 2015-05-01 at 9 07 52 am](https://cloud.githubusercontent.com/assets/62857/7432964/a2d471c8-efe1-11e4-90cb-ee9e30ec9072.png)

**Comment by pydanny** [comment]
Single line change! Old Latex:

``` latex
\usepackage[colorlinks=true,linkcolor=blue,linktoc=page,urlcolor=blue]{hyperref}
```

New LaTeX

``` latex
\usepackage[bookmarksnumbered=true,colorlinks=true,linkcolor=blue,
  linktoc=page,urlcolor=blue]{hyperref}
```

**Comment by gkeller2** [comment]
Glad it was such a tiny change. =)

**Comment by pydanny** [comment]
Ah... but figuring that out took a couple of hours. LaTeX is nothing if not arcane. ;)

**Comment by gkeller2** [comment]
I feared the possibility. Seven years of writing papers and theses in LaTeX taught me not to underestimate the complexities of the tool.

**Comment by pydanny** [comment]
Ha ha. Thing is, there is no tool that compares. Sure, Sphinx/RST and various Markdown tools are handy, but if you want to not have to dig into the nasty, generated LaTeX they use to render PDF, then you have to write the LaTeX by hand.

Which is why my/our next tech book will be written in LaTeX.
