### ISSUE TITLE
Chapter problem with google books

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.8#42]
Reported by @xblitz:

> when I import the PDF to my Google Books library it doesn't seems to recognize the chapters. maybe it's related (to the book mark issue (#41))

**Comment by audreyfeldroy** [comment]
I was able to replicate this.

Can't figure out why it's happening, though. It appears to be an error on Google Books' side, so I wrote up a bug report and sent it to them.

**Comment by pydanny** [comment]
We've been trying to work this out with Google Books for days, but we can't get ahold of their engineering team to help them fix the problem. No other PDF reader has the problems that occur with the Google Books system, so this appears to be a bug in their software.

We suggest using an alternative PDF reader.

**Comment by pydanny** [comment]
For PDF readers, we officially suggest that people use anything but google books.
