### ISSUE TITLE
typo on page 75: "clasmethods"

### ISSUE THREAD

**Issue by ghost** [twoscoops/two-scoops-of-django-1.8#44]
There is a typo on page 75 of the book, where you have written "clasmethods" instead of "classmethods". It is in the first sentence under the heading 6.5 Understanding Fat Models. I've copied it and pasted it here. 

6.5 Understanding Fat Models
􏰁"...e concept of fat models is that rather than putting data-related code in views and templates, instead we encapsulate the logic in model methods, ==> clasmethods <==, properties, even manager..."

**Comment by pydanny** [comment]
:ship:

**Comment by pydanny** [comment]
22f8a70165181c6c47b42865e3ad462ea95b48a9
