### ISSUE TITLE
possibly missing word "ago" page 79

### ISSUE THREAD

**Issue by ghost** [twoscoops/two-scoops-of-django-1.8#45]
In the "WARNING: get object or 404() Is for Views Only" box the first sentence, after the two bullet points begins "Many years a certain Python coder who", however I think that you meant "Many years ago a certain..." which would make the sentence read "Many years a certain Python coder who we won’t list by name, but likes to do cartwheels, was deploying his fi􏰀rst Django project."

**Comment by pydanny** [comment]
:ship:
