### ISSUE TITLE
404 on the cookiecutter URL

### ISSUE THREAD

**Issue by MihailRussu** [twoscoops/two-scoops-of-django-1.8#47]
On Page 21 (the very beginning of Chapter 3, under the first paragraph in "Django Project Templates" "PACKAGE TIP" box), the URL for "A list of alternate cookiecutter templates." is linking to https://www.djangopackages.com/grids/g/cookiecutter/ which doesn't seem to work, instead the  https://www.djangopackages.com/grids/g/cookiecutters/ (letter "s" at the end) does seem to work.

**Comment by pydanny** [comment]
:ship:
