### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by belak** [twoscoops/two-scoops-of-django-1.8#48]
On p72 "it's" should be "its"

On p83 "constatly" should probably be "constantly".

These are both present in the pre-release and Update 1.

I realize you said to split up issues with 2 or more into separate issues, but these both seem trivial enough that it shouldn't be an issue.

**Comment by pydanny** [comment]
Thanks! We'll get them done in the next update. :smile:

**Comment by pydanny** [comment]
:ship:
