### ISSUE TITLE
cookiecutter Template

### ISSUE THREAD

**Issue by marcove3** [twoscoops/two-scoops-of-django-1.8#49]
I am trying to create a new project using:

Example 3.9
$ pip install cookiecutter # Install cookiecutter!
$ cookiecutter https://github.com/pydanny/cookiecutter-django

It is supposed to create a layout like the one in example 3.4, however, example 3.4 shows that the config folder is inside the icecreamratingsfolder, but when I run cookiecutter, the config folder is created inside icecreamratings_project

I think that is an issue unless I am doing something wrong here.

**Comment by pydanny** [comment]
Everything you are doing is correct. :-)

However, cookiecutter-django isn't just the sample template from the book, it's where myself, @theskumar, and @luzfcb sometimes experiment with new concepts and ideas. Sometimes those work out, sometimes they don't. 

Please see https://github.com/pydanny/cookiecutter-django/blob/master/README.rst#for-readers-of-two-scoops-of-django-18
