### ISSUE TITLE
Typo in section title "28.2.3 django.utils.decorators.decorator from middleware("

### ISSUE THREAD

**Issue by timb07** [twoscoops/two-scoops-of-django-1.8#50]
The section title "28.2.3 django.utils.decorators.decorator from middleware(" should omit the trailing "(".

This is present also in the table of contents generated from the section headings.

(This issue is present in both update-1 and the initial release.)

Willfully breaking the two-issues-in-one-issue guideline, I just also spotted what may be a typo in the text of this section (28.2.3): "we can isolate the use of middle on a per-view basis" -- should "middle" be "middleware"?

[And thanks for another great book!]

**Comment by pydanny** [comment]
:ship:

I'm happy you like it. Anything in particular that feels like it's an improvement?
