### ISSUE TITLE
Typo: page 295

### ISSUE THREAD

**Issue by afuna** [twoscoops/two-scoops-of-django-1.8#51]
"for running any function... prefixed with **text_**"

Seems like it should be "**test_**"!

**Comment by afuna** [comment]
bonus on page 296: "lack of inheritence"

**Comment by pydanny** [comment]
:ship:

**Comment by pydanny** [comment]
Can you let us know either here or email your name so we can add you to the acknowledgements in the book?

**Comment by afuna** [comment]
That's unexpected, but cool.

<- Athena Yao

**Comment by pydanny** [comment]
We love to provide attribution. :smile:
