### ISSUE TITLE
Section 32.2.4, ALLOWED_HOSTS

### ISSUE THREAD

**Issue by nbensa** [twoscoops/two-scoops-of-django-1.8#52]
"Unfortunately, as soon as settings.DEBUG is True, a project with an incorrectly set ALLOWED_HOSTS will generate constant 500 errors". 

I think it should say "...DEBUG is **False**..."

**Comment by pydanny** [comment]
:ship:

**Comment by pydanny** [comment]
@nbensa Can you let us know here or in email your name so we can properly provide you with credit in the acknowledgements section of the book?

**Comment by nbensa** [comment]
Of course. My name is Norberto Bensa. Thank you!

**Comment by pydanny** [comment]
No, thank you! :smile:
