### ISSUE TITLE
Wrong links in Section 11.3.1

### ISSUE THREAD

**Issue by ksketo** [twoscoops/two-scoops-of-django-1.8#54]
The two links in this section are not working. Instead of
https://docs.djangoproject.com/en/1.8/ref/contrib/csrf

it should be
https://docs.djangoproject.com/en/1.8/ref/csrf

**Comment by pydanny** [comment]
:ship:

**Comment by pydanny** [comment]
@ksketo Here or in email can you let us know your name so we can properly credit you in the acknowledgements?

**Comment by ksketo** [comment]
@pydanny Sure, it's Konstantinos Faliagkas. Thanks!

Btw, hope you also write the book focusing on Django forms. Looking forward to it! :D
