### ISSUE TITLE
Add mention of code coverage services to chapter 32

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.8#57]
This is one of those things were we're surprised we didn't mention it already!

**Comment by stevepeak** [comment]
I'm thrilled you are mentioning Codecov in your book. It's a great pleasure building this product - so much positive feedback! Thank you @pydanny! Anything that I can do to help please let me know.

**Comment by pydanny** [comment]
:ship:

Notes: Chapter number changed because we added a new chapter before this one.
