### ISSUE TITLE
Possible typo 6.1.4 Database Migrations 

### ISSUE THREAD

**Issue by KTamayo** [twoscoops/two-scoops-of-django-1.8#59]
As of Django 1.7 django.db.migrations replaced the use of the third-party South library, but as both libraries **shared** the same author (Andrew Godwin), usage and practices are quite similar.

Perhaps should be:

As of Django 1.7 django.db.migrations replaced the use of the third-party South library, but as both libraries **share** the same author (Andrew Godwin), usage and practices are quite similar.

**Comment by pydanny** [comment]
:ship:

Could you provide your name for placement in the acknowledgement section of the book? You can either list it here or email me privately at pydanny@gmail.com

**Comment by KTamayo** [comment]
Hello Danny,

I just updated my profile with my name (Karlo Tamayo). I´m reading the book for the first time, thanks for your work!

**Comment by pydanny** [comment]
Hi @KTamayo, you are now in the acknowledgements section of the book. When we do update 2 later today, you can check it out. :smile_cat:
