### ISSUE TITLE
Section 33.2.4 ALLOWED_HOSTS (again)

### ISSUE THREAD

**Issue by nbensa** [twoscoops/two-scoops-of-django-1.8#67]
@pydanny In update-2, there's still one "DEBUG is True" in section 33.2.4. In the middle of the page:

```
So what is happening?

1 settings.DEBUG is True
```

Should read:

```
So what is happening?

1 settings.DEBUG is False
```

**Comment by pydanny** [comment]
Ack. Another `DEBUG` mistake. I blame whatever political party you don't like. 

:ship:
