### ISSUE TITLE
Chapter 25, table 25.2 wrong headers?

### ISSUE THREAD

**Issue by jliendo** [twoscoops/two-scoops-of-django-1.8#68]
Table 25.2 which compares pros and cons of differents task queues to use, seems to have wrong column headers....they read "null=True" and "blank=True"...it looks to me that this is a copy and paste error from the chapter in which the use of null vs blank on model fields is described...

**Comment by pydanny** [comment]
Confirmed! Ack. Blurg.

**Comment by pydanny** [comment]
:ship:
