### ISSUE TITLE
Suggestion: Form.errors.as_data, Form.errors.as_json, and Form.has_error

### ISSUE THREAD

**Issue by michaeljohnbarr** [twoscoops/two-scoops-of-django-1.8#70]
## New in Django 1.7:

[`Form.errors.as_data()`](https://docs.djangoproject.com/en/1.8/ref/forms/api/#django.forms.Form.errors.as_data)

```
>>> f.errors.as_data()
{'sender': [ValidationError(['Enter a valid email address.'])],
'subject': [ValidationError(['This field is required.'])]}
```

[`Form.errors.as_json(escape_html=False)`](https://docs.djangoproject.com/en/1.8/ref/forms/api/#django.forms.Form.errors.as_json)

```
>>> f.errors.as_json()
{"sender": [{"message": "Enter a valid email address.", "code": "invalid"}],
"subject": [{"message": "This field is required.", "code": "required"}]}
```
## New in Django 1.8:

[`Form.has_error(field, code=None)`](https://docs.djangoproject.com/en/1.8/ref/forms/api/#django.forms.Form.has_error)

> This method returns a boolean designating whether a field has an error with a specific error code. If code is None, it will return True if the field contains any errors at all.
> 
> To check for non-field errors use NON_FIELD_ERRORS as the field parameter.

[Example Usage](https://github.com/django/django/blob/4dcc6493418c78db07761180bf6265f5b2bbccbf/tests/forms_tests/tests/test_forms.py#L785-L816) of `Form.has_error(field, code=None)`.

The [`Form.errors.as_data()`](https://docs.djangoproject.com/en/1.8/ref/forms/api/#django.forms.Form.errors.as_data) would be especially useful in tests where you need to check that more than one value is effected. Just a thought. Prior to 1.7, it was somewhat of a pain to retrieve these.

**Comment by pydanny** [comment]
:ship:

Rather than duplicate the Django documentation, we're just linking and encouraging. Also, you got a `Shared with us by Michael Barr` in the form fundamentals chapter.
