### ISSUE TITLE
Suggestion: avoid using locals() as context

### ISSUE THREAD

**Issue by michaeljohnbarr** [twoscoops/two-scoops-of-django-1.8#78]
I have seen many code bases using the following:
## The View

``` python
def some_view(request):
    some_var = 1
    another_var = 2
    return render(request, 'template.html', locals())
```
## The Template

``` html
{% block content %}
    <p>{{ some_var }} and {{ another_var }}</p>
{% endblock content %}
```

I feel it is bad practice, as hiding changing the variable is not immediately apparent. Explicitly assigning these variables to a dictionary of values would be best practice. Good [StackOverflow Answer](http://stackoverflow.com/questions/1901525/django-template-and-the-locals-trick#1901720).

Changing `some_var` to `value` would not be a problem until it no longer showed in the template, which is a silent failure. However, if we did it the "right" way:

``` python

# Before
def some_view(request):
    some_var = 1
    another_var = 2
    return render(request, 'template.html', {'some_var': some_var, 'another_var': another_var})

# After
def some_view(request):
    value = 1
    another_var = 2
    return render(request, 'template.html', {'some_var': some_var, 'another_var': another_var})
```

...we would get an explicit error that the `some_var` variable does not exist.

This may be "out of scope", however, I feel that since we are discussing best practices, it is worth a mention. Why? Because this.

> Explicit is better than implicit.
> Errors should never pass silently.
> Unless explicitly silenced.

**Comment by pydanny** [comment]
I agree. Absolutely. I've had to fix this in the past.

Whether or not we can get it in depends on an issue outside the normal domain of things. In other words, our printer.

**Comment by michaeljohnbarr** [comment]
Ah! Excellent. I'll keep my fingers crossed. Thanks!

**Comment by pydanny** [comment]
:ship:
