### ISSUE TITLE
Chapter 32 - development workfl􏰂ow, section 2 - unnecessary 'not'

### ISSUE THREAD

**Issue by bogdal** [twoscoops/two-scoops-of-django-1.8#79]
Section 2 says:
Th􏰀e code repository informs an automation tool that code has **not** been submitted for integration.

I think we shouldn't use `not` here, because the code repository informs about new code which should be integrated in the next step. I'm right?

**Comment by audreyfeldroy** [comment]
Fixed, thanks @bogdal.
:ship:
