### ISSUE TITLE
Discuss _meta API

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.8#8]

**Comment by phalt** [comment]
If you weren't already, I think adding a section on how to support the old deprecated _meta methods with the new _meta API would be useful :)

**Comment by pydanny** [comment]
@phalt Maybe with a suggested a shim library? Sort of like a `six` or `futures` but for Django's _meta API?

**Comment by phalt** [comment]
@pydanny Does one exist? That's a great idea.

**Comment by pydanny** [comment]
Creating something like that is completely outside our bandwidths, but we'll cheer on the efforts of others.

**Comment by phalt** [comment]
@pydanny I meant talking about one, if one existed, being a great idea :)

**Comment by pydanny** [comment]
:ship:
