### ISSUE TITLE
Suggestion for 33.2.2 Mirroring Production, take special care with email addresses

### ISSUE THREAD

**Issue by ludw** [twoscoops/two-scoops-of-django-1.8#81]
In the checklist in 33.2.2 Mirroring Production you mention removing Personally Identifying Information, which is a great idea. 

I would like to suggest adding something about taking special care with email addresses. They might not seem like a big deal to keep around on your dev server, but all it takes is one small misshap and you have sent emails to all of your users.

**Comment by audreyfeldroy** [comment]
This is a fantastic suggestion, thanks. I've added it to the PII item and also quoted your last sentence in a box. :ship:
