### ISSUE TITLE
Suggestion: information about setting up database, especially PostgreSQL users/permissions

### ISSUE THREAD

**Issue by HiGregSmith** [twoscoops/two-scoops-of-django-1.8#84]
As a new user, I'm using the book to learn Django (as well as from the official Django documentation). I want to set up a multi-site Django project and am trying to figure out how to do so. That is, when setting up multiple sites served from a set of Django projects, some will share databases, and some will not. Advice in the book on setting up users/group roles/login roles for (in my case) PostgreSQL would be a welcome addition. And, further, how to set up the DATABASES setting accordingly.

As a reference, this short web page seems the most appropriate that I've found:
http://killtheyak.com/use-postgresql-with-django-flask/

Excellent book at the perfect, and very usable, level!!

**Comment by pydanny** [comment]
Unfortunately, this won't make it into the book. Here's why:
1. Database setup for PostgreSQL (or MySQL, Oracle, etc) is arguably outside the scope of Two Scoops of Django. In the 1.8 edition we actually removed content that existed in previous editions, as we were trying to narrow the scope further (yet we're still over 500 pages). 
2. Considering the low cost of virtual machines and the easier deployment systems of modern day configuration management, we feel it doesn't make much sense to serve multiple sites from a single Django project. While there are edge cases, those are unique and often don't even need the `django.contrib.sites` framework.
3. Multiple databases for a single project might prove to be something we include in the next edition of Two Scoops of Django.

In any case, we really appreciate your through provoking submission. :smile:
