### ISSUE TITLE
Grammar: Missing word under Section 19.3?

### ISSUE THREAD

**Issue by patpatpatpatpat** [twoscoops/two-scoops-of-django-1.8#85]
Under `19.3 Viewing String Representations of Objects`,

The second sentence above `Example 19.3` is:

`For working in Python 2.7, Django also provides...`

I think it should be:

`For those working in Python 2.7` or `For those working with Python 2.7`.

---

P.S: Thank you so much for this incredible book!!!!

**Comment by pydanny** [comment]
This one of those statements of grammar which can go either way. We prefer the existing phrasing as it's a little less formal.

Thanks for the submission! :smile:

**Comment by patpatpatpatpat** [comment]
:+1: no problem!
