### ISSUE TITLE
Typo in 1.6.2 (update 4) regex

### ISSUE THREAD

**Issue by bassemali** [twoscoops/two-scoops-of-django-1.8#86]
Just started reading through update 4. There's a regex represented as `âdd-topping/$` when I believe it should be `^add-topping/$`.

![screen shot 2015-05-28 at 1 42 50 pm](https://cloud.githubusercontent.com/assets/210470/7866804/c99ed9c4-053f-11e5-84a4-db606787ebb4.png)

Enjoying the read so far, thanks for the book!

:icecream:

**Comment by cateee** [comment]
BTW I think the entire section is obsolete. String views in URL are considered obsolete, so it seems that you are recommending to use string view (just with a pythonic style)

**Comment by pydanny** [comment]
:ship:

**Comment by pydanny** [comment]
@cateee `String views` in URLs are considered obsolete? What are `string views`?
