### ISSUE TITLE
Discuss PostgreSQL specific fields

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.8#9]
NEW CHAPTER!!
- General
  - Always validate incoming data with field
- ArrayField
  - Delimiter issues
  - Storing lists of big datatypes is not such a good idea
- HStore
  - Always validate with field
  - Don't reference primary keys from HSTORE. That's what foreign key fields are for.
- RangeFields

**Comment by pydanny** [comment]
Question: Should django.contrib.postgres be in it's own chapter or appendix? The models chapter is already 20 pages long and this is very database specific.

**Comment by auvipy** [comment]
I belive that should be on a different chapter naming "DB specific features"

**Comment by pydanny** [comment]
We've decided to go with having just a chapter on PostgreSQL. If a `django.contrib.mysql` ever happens we'll consider adding it to the ice cream mix.

**Comment by pydanny** [comment]
:ship: 

Rather than make this its own chapter, we broke up the Models chapter into two chapters:
1. Models
2. Queries

The PostgreSQL stuff is in both of them.
