### ISSUE TITLE
7.3 Bad Example 7.1 Cut off in print version

### ISSUE THREAD

**Issue by michaeljohnbarr** [twoscoops/two-scoops-of-django-1.8#90]
`return Promo.objects.active().filter(Q(name__startswith=name)|Q(descript` is what shows in the book.

Perhaps we can do some clever wrapping:

```
return Promo.objects.active().filter(
    Q(name__startswith=name) |
    Q(description__icontains=name)
)
```

**Comment by michaeljohnbarr** [comment]
Never mind - foolish mistake on my behalf. You are demonstrating how query chaining makes code go off the page...

**Comment by pydanny** [comment]
;)
