### ISSUE TITLE
Chapter 10.5.1 Example 10.9 - missing/invalid import

### ISSUE THREAD

**Issue by michaeljohnbarr** [twoscoops/two-scoops-of-django-1.8#93]
```
@property
def success_message(self):
    return NotImplemented
```

There is no import for `NotImplemented`. My guess is that we should be doing:

```
@property
def success_msg(self):
    raise NotImplementedError('No success_message')
```

Alternatively, Django actually provides the [`django.contrib.messages.views.SuccessMessageMixin`](https://docs.djangoproject.com/en/1.8/ref/contrib/messages/#adding-messages-in-class-based-views) which does nearly the same thing as the example, except that it uses `messages.success` instead of `messages.info`:

```
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import CreateView
from myapp.models import Author

class AuthorCreate(SuccessMessageMixin, CreateView):
    model = Author
    success_url = '/success/'
    success_message = "%(name)s was created successfully"
```
#### django.contrib.messages.views.SuccessMessageMixin

```
from django.contrib import messages

class SuccessMessageMixin(object):
    """
    Adds a success message on successful form submission.
    """
    success_message = ''

    def form_valid(self, form):
        response = super(SuccessMessageMixin, self).form_valid(form)
        success_message = self.get_success_message(form.cleaned_data)
        if success_message:
            messages.success(self.request, success_message)
        return response

    def get_success_message(self, cleaned_data):
        return self.success_message % cleaned_data
```

**Comment by michaeljohnbarr** [comment]
Follow-up: I was unaware that `NotImplemented` is a type in Python. Neat. Thus, the basis of this particular issue may actually be baseless.

**Comment by pydanny** [comment]
Yes, but `SuccessMessageMixin` makes the example not as good as we would like. Working on it.

**Comment by pydanny** [comment]
Modified to be a better example in 1.11.
