### ISSUE TITLE
"Don't do this" in a light grey box

### ISSUE THREAD

**Issue by HiGregSmith** [twoscoops/two-scoops-of-django-1.8#94]
(Page number refers to Release version 1.8 PDF, this is derived from my PDF notes on Kindle.)

Section 7.3

Two Scoops of Django_ Best Practices for Django 1.8  
- Your Note on page 84 | Added on Friday, June 5, 2015 7:31:30 PM

Says "Don't do this" in a light grey box. Maybe should remove this comment line because it doesn't apply to the light grey box.

**Comment by pydanny** [comment]
:ship:

**Comment by pydanny** [comment]
This was fixed in the India edition, but not corrected in the standard edition.

**Comment by pydanny** [comment]
:ship:
