### ISSUE TITLE
"Eventual consistency"?

### ISSUE THREAD

**Issue by HiGregSmith** [twoscoops/two-scoops-of-django-1.8#95]
Section 7.7.1

(Page number refers to Release version 1.8 PDF, this is derived from my PDF notes on Kindle.)

"eventual consistency rather than for transactional integrity. In other words, be prepared for transactions to fail and rollbacks to occur."

Two Scoops of Django_ Best Practices for Django 1.8  
- Your Note on page 92 | Added on Saturday, June 6, 2015 12:01:17 PM

These two phrases seem to say the opposite. "eventual consistency" implies to me that immediate consistency is less important. That is, allow autocommit instead of wrapped transactions. This interpretation, according to context, wrong.

**Comment by pydanny** [comment]
I could be wrong, but I think you are taking a portion of text out of context. If you look at the entire paragraph instead of a segment, then it makes sense:

> Tipbox title: Projects Touching Medical or Financial Data
> For these kinds of projects, engineer systems for eventual consistency rather than for transactional integrity. In other words, be prepared for transactions to fail and rollbacks to occur. Fortunately, because of transactions, even with a rollback, the data will remain accurate and clean.

Again, I could be wrong and am open to suggestions on how to better phrase it.

**Comment by pydanny** [comment]
Please reopen if you think this can be addressed better.
