### ISSUE TITLE
word "subsection" repeated

### ISSUE THREAD

**Issue by HiGregSmith** [twoscoops/two-scoops-of-django-1.8#96]
(Page number refers to Release version 1.8 PDF, this is derived from my PDF notes on Kindle.)

Section 7.7.2

Two Scoops of Django_ Best Practices for Django 1.8  
- Your Note on page 93 | Added on Friday, June 5, 2015 8:20:48 PM

repeated word "subsection subsection 24.2.4"
(The second word is part of the reference link, while the first is preceding the reference).

**Comment by pydanny** [comment]
:ship:
