### ISSUE TITLE
Word "transactions" confusing by itself.

### ISSUE THREAD

**Issue by HiGregSmith** [twoscoops/two-scoops-of-django-1.8#97]
(Page number refers to Release version 1.8 PDF, this is derived from my PDF notes on Kindle.)

Section 7.7.2 (within "TIP: Never Wrap Individual ORM Method Calls")
"Instead, use transactions when you are calling several ORM methods..."

Two Scoops of Django_ Best Practices for Django 1.8  
- Your Note on page 93 | Added on Saturday, June 6, 2015 12:06:42 PM

perhaps more precisely "explicit transactions"

In general, the word "transactions" by itself is confusing because it doesn't delineate implicit line-by-line transactions vs. "wrapped" or "explicit" transactions. I prefer the adjective "explicit".

**Comment by pydanny** [comment]
:ship:
