### ISSUE TITLE
Two Scoops 1.8 layout vs cookiecutter-django layout

### ISSUE THREAD

**Issue by stepmr** [twoscoops/two-scoops-of-django-1.8#98]
Hi guys,
I know there are warnings about differences between the project layout in the book and django-cookiecutter and regarding the EOL of django-twoscoops-project... but for me the difference in layout was disjunctive (not so much the extras etc) - especially after the convincing demonstration of a three-tiered scoop.  Maybe a quick note could be appended to cookiecutter-django about why the cookiecutter-django directory structure is different?
## Two Scoops 1.8 preferred layout
- repository_root
  - django_project_root
    - configuration_root
## cookiecutter-django
- repository_root
  - django_project_root
  - configuration_root

**Comment by pydanny** [comment]
There is already https://github.com/pydanny/cookiecutter-django#for-readers-of-two-scoops-of-django-18

That said, I'm not too happy myself with the experiment we've chosen. We'll probably switch back shortly.
